// Datos de los 31 catálogos de Innova
// palette: { bg, accent, ink } — colores cálidos por categoría
// pattern: tipo de patrón SVG (dots | waves | diamonds | stripes | blob | stars | grid | triangles | confetti | scribble | hatching)
// featured: marcado como destacado en orden por defecto

window.INNOVA_CATALOGS = [
  { id: "Futbol", name: "Argentina Futbol Mundial", count: 47, featured: true,
    palette: { bg: "#0F2A4E", accent: "#D4AF6A", ink: "#F6EFD8" }, pattern: "stars" },
  { id: "Boho", name: "Boho", count: 412, featured: true,
    palette: { bg: "#C56A4B", accent: "#F4E6D2", ink: "#FFF6E9" }, pattern: "waves" },
  { id: "Escolar", name: "Escolar", count: 286, featured: false,
    palette: { bg: "#1E3A5F", accent: "#E8DCC4", ink: "#F4ECD7" }, pattern: "grid" },
  { id: "Infantiles", name: "Infantiles", count: 648, featured: true,
    palette: { bg: "#F2C879", accent: "#E8A4B0", ink: "#3D2A1F" }, pattern: "confetti" },
  { id: "Fluo", name: "Fluo", count: 156, featured: false,
    palette: { bg: "#1A1414", accent: "#D4F25A", ink: "#F6FBC6" }, pattern: "dots" },
  { id: "Newborn", name: "Newborn", count: 524, featured: true,
    palette: { bg: "#E5C5B5", accent: "#C99E87", ink: "#4A2E22" }, pattern: "blob" },
  { id: "Glitter", name: "Glitter y Shimmer", count: 198, featured: true,
    palette: { bg: "#C896A8", accent: "#D8B886", ink: "#FBEEDB" }, pattern: "confetti" },
  { id: "Abstractas", name: "Texturas Abstractas", count: 467, featured: true,
    palette: { bg: "#B58947", accent: "#756241", ink: "#F8ECCF" }, pattern: "blob" },
  { id: "Ventana", name: "Ventana", count: 92, featured: false,
    palette: { bg: "#8FA5B0", accent: "#ECE0CC", ink: "#F7EFDB" }, pattern: "grid" },
  { id: "Pascuas", name: "Pascuas", count: 78, featured: false,
    palette: { bg: "#E9D4A0", accent: "#B8C49C", ink: "#3D3520" }, pattern: "dots" },
  { id: "san_valentin", name: "San Valentín", count: 86, featured: false,
    palette: { bg: "#7A2E3C", accent: "#D89AA8", ink: "#FBE0DE" }, pattern: "blob" },
  { id: "Fachada", name: "Fachada", count: 147, featured: false,
    palette: { bg: "#A85B4A", accent: "#D4B898", ink: "#F6EBD7" }, pattern: "stripes" },
  { id: "BabyShower", name: "Baby Shower", count: 312, featured: false,
    palette: { bg: "#C5D4DC", accent: "#F0E5D2", ink: "#2F3F4A" }, pattern: "confetti" },
  { id: "Escaleras", name: "Escaleras", count: 73, featured: false,
    palette: { bg: "#B8A893", accent: "#6F5E4E", ink: "#FBF3E2" }, pattern: "stripes" },
  { id: "Mascotas", name: "Mascotas (InnPets)", count: 348, featured: true,
    palette: { bg: "#E8B591", accent: "#A85F3F", ink: "#3D2418" }, pattern: "triangles" },
  { id: "Urbano", name: "Urbano", count: 218, featured: false,
    palette: { bg: "#3A3530", accent: "#C68A3E", ink: "#F6E4C2" }, pattern: "hatching" },
  { id: "Texturas", name: "Texturas", count: 689, featured: false,
    palette: { bg: "#A66C4B", accent: "#C49866", ink: "#FBEAD0" }, pattern: "blob" },
  { id: "Bosque", name: "Bosque", count: 174, featured: false,
    palette: { bg: "#4A6048", accent: "#91A082", ink: "#F0EBD0" }, pattern: "scribble" },
  { id: "Boliche", name: "Disco · Recitales", count: 108, featured: false,
    palette: { bg: "#5A3373", accent: "#E84C9A", ink: "#FCDFEB" }, pattern: "dots" },
  { id: "halloween", name: "Halloween", count: 134, featured: false,
    palette: { bg: "#2A1F1A", accent: "#C8642A", ink: "#F6CC8E" }, pattern: "triangles" },
  { id: "Bautismo", name: "Comunión y Bautismo", count: 187, featured: false,
    palette: { bg: "#ECDFC6", accent: "#B89653", ink: "#5C4626" }, pattern: "stars" },
  { id: "Alas", name: "Alas", count: 62, featured: false,
    palette: { bg: "#DEB8B5", accent: "#F0E2D5", ink: "#4E2F2C" }, pattern: "waves" },
  { id: "Lunas", name: "Lunas y Estrellas", count: 256, featured: true,
    palette: { bg: "#2C3554", accent: "#C8A858", ink: "#F4E3B5" }, pattern: "stars" },
  { id: "Paredes", name: "Paredes", count: 512, featured: false,
    palette: { bg: "#C2B5A3", accent: "#8C7C68", ink: "#FBF3E2" }, pattern: "grid" },
  { id: "Globos", name: "Globos", count: 224, featured: false,
    palette: { bg: "#E8B5B5", accent: "#A86F6F", ink: "#FCE7E7" }, pattern: "dots" },
  { id: "Hojas", name: "Hojas", count: 196, featured: false,
    palette: { bg: "#9CB088", accent: "#5C6E48", ink: "#F2EDDB" }, pattern: "scribble" },
  { id: "Castillo", name: "Castillo", count: 48, featured: false,
    palette: { bg: "#6E3A4D", accent: "#C898A8", ink: "#FBE5EE" }, pattern: "diamonds" },
  { id: "Empresariales", name: "Empresariales", count: 174, featured: false,
    palette: { bg: "#3C3D40", accent: "#A8A096", ink: "#F4EDDF" }, pattern: "grid" },
  { id: "Pisos", name: "Pisos", count: 386, featured: false,
    palette: { bg: "#D8C0A4", accent: "#A87D5C", ink: "#3F2E1F" }, pattern: "stripes" },
  { id: "coloridos", name: "Fondos Coloridos", count: 578, featured: true,
    palette: { bg: "#F2A65A", accent: "#C84B8A", ink: "#FFF6E9" }, pattern: "diamonds" },
  { id: "Egresados", name: "Egresados", count: 152, featured: false,
    palette: { bg: "#20355A", accent: "#C49C58", ink: "#F4E5C0" }, pattern: "confetti" },
];

window.INNOVA_TOTAL_DESIGNS = window.INNOVA_CATALOGS.reduce((s, c) => s + c.count, 0);
